### ISSUE TITLE
Messages not published

### ISSUE THREAD

**Issue by NiR-** [M6Web/AmqpBundle#11]
Hi there, 

I am trying to use a producer which is bound to direct exchange, but I am facing two bugs :
* With the `delivery_mode` parameter set to `persistent`, it seems that the exchange never receive the messages.
* And when this option is not use, whether the queue has been manually created (`rabbitmqadmin declare exchange name='campaign_analysis' type='direct' && rabbitmqadmin declare queue name='campaign_analysis'`) or not, the first message is not published (but the following are correctly published). I've also tried with 'amq.direct' exchange, but I have the same behavior.

Here is my current config :
```yaml
m6_web_amqp:
    event_dispatcher: false
    connections:
        default:
            host:     %amqp_host%
            port:     %amqp_port%
            timeout:  %amqp_timeout%
            login:    %amqp_user%
            password: %amqp_password%
            vhost:    %amqp_vhost%
            lazy:     false
    producers:
        campaign_analysis:
            connection: default
            exchange_options:
                name: 'campaign_analysis'
                type: direct
                routing_keys: ['campaign_analysis']
                publish_attributes:
                    content_type: 'application/json'
                    #delivery_mode: 'persistent'
    consumers:
        campaign_analysis:
            connection: default
            exchange_options:
                name: 'campaign_analysis'
            queue_options:
                name: 'campaign_analysis'
                durable: true
                routing_keys: ['campaign_analysis']
```

Any help would be appreciated :)

EDIT: I have tried this simple POC and it seems to work fine :
```php
<?php

$conn = new AMQPConnection();
$conn->setHost('localhost');
$conn->setPort(5672);
$conn->setLogin('guest');
$conn->setPassword('guest');
$conn->setVhost('/');
$conn->connect();

$ch = new AMQPChannel($conn);

$ex = new AMQPExchange($ch);
$ex->setName('amq.direct');
$ex->setType(AMQP_EX_TYPE_DIRECT);
$ex->setFlags(AMQP_DURABLE);
$ex->declare();

$q = new AMQPQueue($ch);
$q->setName('campaign_analysis');
$q->declare();
$q->bind('amq.direct', 'campaign_analysis');

$ex->publish('Hi there!', 'campaign_analysis');

// var_dump($q->get(AMQP_AUTOACK));
```
